// AUTO-GENERATED by scripts/process-assets.mjs — do not edit by hand.
// Re-run `npm run assets` to regenerate after adding/changing source media.

export type MediaAsset = {
  slug: string;
  width: number;
  height: number;
  aspect: number;
  widths: readonly number[];
  blurDataURL: string;
  alt: { en: string; ar: string };
};

export const MEDIA = {
  "nawaiseh-credentials": {
    slug: "nawaiseh-credentials",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQBACdASoUABkAPzmOuFcvKaUjqA1R4CcJZQAALYftC78QLGc4myNLBJ45eRSeYAD+6M/kepwxkIEaEpXP2LBGVPcgqmTQ+oKz/pXIuMIc0l6QMqN9o2swHxpfFThvBkNxf0QRdnc0MChgaQiLIeeYUJCSSRGUETCiIHbPtC6MYMQsxm3aG2mHnT1BNc7HZ6LANAAA",
    alt: { en: "Instagram credential graphic for Ahmad Al-Nawaiseh, Theeb Fitness's coaching director, listing his sports-training degrees, IFBB Pro League judge certification and 19+ years of experience", ar: "بطاقة اعتماد من إنستغرام لأحمد النوايسة، مدير التدريب في ذيب فيتنس، توضح شهاداته في التدريب الرياضي واعتماده حكمًا دوليًا في IFBB Pro League وخبرته التي تتجاوز 19 عامًا" },
  },
  "nawaiseh-portrait": {
    slug: "nawaiseh-portrait",
    width: 460,
    height: 575,
    aspect: 0.8,
    widths: [153, 230, 345, 460],
    blurDataURL: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoUABkAPzGAs1OuqCSisAwB0CYJQBlakRgr93oLjzwSgKmro7lFWICAAP5zQILGQklrMH+LIoAXHSAtZC13wkpuc+nOhipooDASC6iC1i7BZAsHiQbtF6ISTiOfc4W1ROES6Ct2VeQF149uiq6qhLl9I/eyGRIneFuSegAAAAA=",
    alt: { en: "Close portrait of Ahmad Al-Nawaiseh, owner and coaching director of Theeb Gym, smiling with arms crossed in a Theeb Fitness polo shirt", ar: "صورة مقرّبة لأحمد النوايسة، مالك ومدير التدريب في ذيب جيم، يبتسم وذراعاه متقاطعتان بقميص ذيب فيتنس" },
  },
  "nawaiseh-judging": {
    slug: "nawaiseh-judging",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQDDRf/gFjFLexM/QADNmNLubj20d945/x8sPEjVfIKhzKu10Y24XdUiQGAhd+zX0qs2AqTObVf+pwRlM4534uj6JGyW7K1jo0mYyxhrndKfChFSe19UYMR0K2zA0oDlUERAAAA=",
    alt: { en: "Ahmad Al-Nawaiseh signing scorecards at the judges' table beside a competitor backstage at an IFBB Pro League bodybuilding show", ar: "أحمد النوايسة يوقّع بطاقات التحكيم على طاولة الحكام بجانب أحد المتنافسين خلف الكواليس في بطولة IFBB Pro League لكمال الأجسام" },
  },
  "nawaiseh-conference": {
    slug: "nawaiseh-conference",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoUABkAPzmQvlevKaYjqAqp4CcJZgCdAA9IX6MqFdOugUflquqR3zAA/p/Z2wWHB4pZSwKopoJSvUMNAVMmShZNxRkS3/aeJufeljhyFnBOClts91ckT9jdbwD/7is5BGp6nKPMfuUnQCgHKvV6dCl3wmA3FT0o8O4p78IVWPrZ7/bVCd8AAA==",
    alt: { en: "Ahmad Al-Nawaiseh speaking at a lectern with a wireless microphone during a sports conference", ar: "أحمد النوايسة يتحدث خلف منصة بميكروفون لاسلكي خلال مؤتمر رياضي" },
  },
  "nawaiseh-stage-tunisia": {
    slug: "nawaiseh-stage-tunisia",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJQBWEDjE/wIDS7sxi3ywA90HgrfUUZdKyqrxeV3K02T4AzHtl0Pir7JHBaJctzWIl0plL6RzA9REMyqetoWkJraKnZV4UVJ9tHINOAUKwkVcyofqBbEAQAAA=",
    alt: { en: "Ahmad Al-Nawaiseh on stage with fellow officials at an IFBB-affiliated bodybuilding championship in Tunisia", ar: "أحمد النوايسة على المسرح مع مسؤولين آخرين في بطولة لكمال الأجسام تابعة لـ IFBB في تونس" },
  },
  "nawaiseh-award-stage": {
    slug: "nawaiseh-award-stage",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQAAMOoXj76tehzUBoAD+JpbMuxt7gjzWdXrClDGJhVbPOaDIkP0MaUf0m9ErUd192RrUTyhHm3Rb3c1LardXqOYibWPzPt9oHroNa8+wgAmFRznJAAAA",
    alt: { en: "Ahmad Al-Nawaiseh among a lineup of judges and officials holding trophies on stage at an international bodybuilding show", ar: "أحمد النوايسة ضمن صف من الحكام والمسؤولين يحملون الجوائز على المسرح في بطولة دولية لكمال الأجسام" },
  },
  "nawaiseh-judging-tunisia": {
    slug: "nawaiseh-judging-tunisia",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQAALb6qftNE/GK6qAAD+4urA8Kmg/0qGADYE8ijBhgRbdlXjfYXBdC1gqP1mupLEcbi4vPtXHZDkQth1kb/+QtMf+HlwEAwEOpPdmVlBepgA",
    alt: { en: "Ahmad Al-Nawaiseh and fellow IFBB Pro League judges posing on stage at a professional bodybuilding championship in Tunisia", ar: "أحمد النوايسة وزملاؤه حكام IFBB Pro League في وقفة على المسرح خلال بطولة احترافية لكمال الأجسام في تونس" },
  },
  "nawaiseh-speaking-libya": {
    slug: "nawaiseh-speaking-libya",
    width: 1170,
    height: 779,
    aspect: 1.5019,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJbACdABuWaGkwhB3RAAD+qaaW6cXsM9v9EeTFrpGAtPIQaX6pxZyQyZ4Lu3gMw/22g+pSL/WUPWs5y2XY3+E/ZAKWxqkGV0bpUU0QAAA=",
    alt: { en: "Ahmad Al-Nawaiseh speaking on stage with a microphone at the Ashoor Classic bodybuilding show in Libya", ar: "أحمد النوايسة يتحدث على المسرح بالميكروفون في بطولة عاشور كلاسيك لكمال الأجسام في ليبيا" },
  },
  "coach-aladaileh": {
    slug: "coach-aladaileh",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoUABkAPzmKvFUvKSYjKA1R4CcJYwAALWOrPHZHQZxKK6tPKfPOGHAA/ujP5HqcMZJlywnt50T2oI7YrxwU4jqLa2M4FecC3LIIf0DjuZ8+6NmTBJ6d0gnJ38jWmXe+oCoQwcz7MJzSFZCWzLZj6bp1dNch2EznAAQ/kwuaqW7FJsEZzpp892YAuBAAAA==",
    alt: { en: "Portrait of a coach at Theeb Gym, standing with arms crossed in a Theeb Fitness T-shirt", ar: "صورة لأحد المدربين في ذيب جيم، واقفًا وذراعاه متقاطعتان بقميص ذيب فيتنس" },
  },
  "coach-khoury": {
    slug: "coach-khoury",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwBACdASoUABkAPzmIu1avKCWjsBgIAeAnCUAABbVW9o8e3fVxnj+Y7yMJuYJsZgAA/ujP5HqcMXw5PHu/URNN0PIwDHi5ic99cR6sm7Rz0D48XuKFk7VuVCpb2IIgSij9drneeR2kJZ/tSEqIWkTZAbFUxShQvezkLoDRlDlroXCrCz66mAAA",
    alt: { en: "Portrait of a coach at Theeb Gym, standing with arms crossed in a Theeb Fitness T-shirt", ar: "صورة لأحد المدربين في ذيب جيم، واقفًا وذراعاه متقاطعتان بقميص ذيب فيتنس" },
  },
  "facility-machines": {
    slug: "facility-machines",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBQCdASoUABkAPzmOwFcvKacjqAqp4CcJbAC7AywAxICvqLwV22OLbNX6yuiHED9lwAD+40TD3hU3FZPd4c4zIbqgDlQ+/BCFqLSrnRU0QOIx5UBOsTHv39+t4kUIXKhtZKc2s6OjOVJld77nz3J3TLha31nbd4NM9V44SJN8nfsfkf32E3xLXZ+vY2obZid3UGEf9sAAAA==",
    alt: { en: "Theeb Gym promotional graphic over a photo of the training floor, highlighting more than 250 machines from leading global equipment brands", ar: "بطاقة ترويجية من ذيب جيم فوق صورة لصالة التدريب، تُبرز أكثر من 250 جهاز رياضي من أقوى الماركات العالمية" },
  },
  "facility-space": {
    slug: "facility-space",
    width: 1080,
    height: 1350,
    aspect: 0.8,
    widths: [360, 540, 810, 1080],
    blurDataURL: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwBACdASoUABkAPzmWwVovKqckKAgB4CcJagDHMBEcIQUDqeGdSyXbzyF3GtLAKAAA/ti/8hhBrMsHFAwR6eC6/M7U9Lzkb0/2VOQZ/OEYCzXR4sx4+CbAg0rNqr2GWHFpkaYHVhhaNejBkHXJ1nY1CLgBnXBjQAA=",
    alt: { en: "Theeb Gym promotional graphic over a photo of the training floor, highlighting the 2,000 square metre integrated sports space", ar: "بطاقة ترويجية من ذيب جيم فوق صورة لصالة التدريب، تُبرز مساحة رياضية متكاملة تبلغ 2000 متر مربع" },
  },
  "gallery-01": {
    slug: "gallery-01",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwAAKuPFSUTkAAD+qTAL3T7e9emCdenjA88ogalsOZTHYxTA/qVsNmcI0Dvf1Kq1zt0w/zsdoUxoAAA=",
    alt: { en: "A row of plate-loaded leg press and iso-lateral press machines beside floor-to-ceiling windows overlooking the street", ar: "صف من أجهزة الضغط بالأثقال (ليغ برس) وأجهزة الضغط الجانبي بجانب نوافذ ممتدة من الأرض إلى السقف تطل على الشارع" },
  },
  "gallery-02": {
    slug: "gallery-02",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZwAAXlR5OpHqWwPCAAD+hkPPfbIGJ9lNpXv4e0qMrKw+dsk0cJVvtpmnyLmaLixqYNND6oNfynZ8hwlWg5mAAAA=",
    alt: { en: "A red iso-lateral row machine and an adjustable bench on the training floor, with a staircase leading up to the mezzanine", ar: "جهاز تجديف جانبي أحمر ومقعد قابل للتعديل في صالة التدريب، مع درج يؤدي إلى الميزانين" },
  },
  "gallery-03": {
    slug: "gallery-03",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZwAAUyJoeiIIAP4XWzUstjcrZW561uoJtmeJ3JLxUyAHHbmaw6Hk8b6bUr+A3gii+Ugz3WnzqH4AAAA=",
    alt: { en: "Loaded barbells and weight plates on storage racks in front of a mirrored wall reflecting the gym floor", ar: "قضبان حديد وأوزان محملة على حوامل تخزين أمام حائط مرايا يعكس صالة الجيم" },
  },
  "gallery-04": {
    slug: "gallery-04",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQBadAfGDTyr8ZkngAAD+0KHqgqK29zosuog0FBURp3pRQBil2P2YmTjMb23VxMC2ex6agAA=",
    alt: { en: "A cardio corner with StairMaster climbers, stationary bikes and a yellow-framed functional training rig, with agility lines marked on the floor", ar: "ركن للتمارين الهوائية يضم أجهزة StairMaster ودراجات ثابتة وهيكل تدريب وظيفي بإطار أصفر، مع خطوط رشاقة مرسومة على الأرض" },
  },
  "gallery-05": {
    slug: "gallery-05",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAA0APzmIuVQvKSWjMAgB4CcJaQAAW2/67dbrphAA/qnB1CuYo/skoHGZrdsQwzIXZbIAAAA=",
    alt: { en: "Hammer Strength dumbbell racks and Theeb-branded weight plates beside a mirrored corner of the gym", ar: "حوامل دمبل من ماركة Hammer Strength وأوزان تحمل شعار ذيب بجانب ركن مرايا في الجيم" },
  },
  "gallery-06": {
    slug: "gallery-06",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZwDE2BdfnEQM3KAAAP7NCGktoqTtJz0TPlX1YVBtvsanlpXj8X02uFQM9WBGF2FAAA==",
    alt: { en: "A wide view of the training floor with plate-loaded machines around a support column and a staircase up to the mezzanine level", ar: "منظر واسع لصالة التدريب يضم أجهزة محملة بالأثقال حول عمود داعم ودرج يؤدي إلى مستوى الميزانين" },
  },
  "gallery-07": {
    slug: "gallery-07",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZwAAXBgMNgn1QXaJgAD+gY3LRlIxUmeN1RWs/lF4TeSV5UYfVGO7VJX8grgE+FU6gc4+KSn6AAAA",
    alt: { en: "A red plate-loaded leg press machine and other equipment lined up along the window wall", ar: "جهاز ليغ برس أحمر محمل بالأثقال وأجهزة أخرى مصطفة على طول حائط النوافذ" },
  },
  "gallery-08": {
    slug: "gallery-08",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJaQAAV/yqrJAA/r/HzDmIYSYJMLVo/UCdqN+OiPQy5ctHg4rw2vhvrJnvAAAA",
    alt: { en: "An elevated view of the free-weight floor with a leg press, leg curl station and a chrome plate tree", ar: "منظر علوي لصالة الأوزان الحرة يضم جهاز ليغ برس ومحطة لتمرين الفخذ الخلفي وحامل أقراص من الكروم" },
  },
  "gallery-09": {
    slug: "gallery-09",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQC/OB4jFzD1IeOEBnQAAP6BiSQ9s37GM7ggDQi42PVp1Lb3tigP401VAPuR4t5pAAAA",
    alt: { en: "A Life Fitness multi-station cable trainer on the gym floor with cardio machines and dumbbell racks in the background", ar: "جهاز كابل متعدد المحطات من Life Fitness في صالة الجيم مع أجهزة كارديو وحوامل دمبل في الخلفية" },
  },
  "gallery-10": {
    slug: "gallery-10",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAA0APzmGuVQvKSWjMAgB4CcJZQAAR9w1OyYkjIAA/tCUZX2LP/XEwHgy4fOenx45G6tdotAymOpzNcQEE3gnJj3Yy/dKO7dcyKwAAAA=",
    alt: { en: "A yellow functional-training rig hung with colourful kettlebells and resistance bands, with an Arabic wolf wall sign behind it", ar: "هيكل تدريب وظيفي أصفر معلق عليه أثقال كيتل بألوان متعددة وأحزمة مقاومة، وخلفه لافتة جدارية بعبارة الذئب بالعربية" },
  },
  "gallery-11": {
    slug: "gallery-11",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQBWABaD7yp7AAP7qGvMRnFnxhXbn9lTzscQxrJSDtcXES+mLDtLoVesMHyZI8diUyHZJqrjaIexMHCuXVE1mUAA=",
    alt: { en: "A row of Hammer Strength dumbbell racks beside the windows with olympic weight plates on the floor", ar: "صف من حوامل دمبل Hammer Strength بجانب النوافذ مع أقراص أوزان أولمبية على الأرض" },
  },
  "gallery-12": {
    slug: "gallery-12",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJaQAASjN6EW5b0R8AAP7ABbfqlMckOJrCFPD0l/bokFUF77sEKFspmHwUqOF6jgA=",
    alt: { en: "Chrome-plated dumbbell and weight racks fully stocked along the training floor", ar: "حوامل دمبل وأوزان مطلية بالكروم ومكتملة على طول صالة التدريب" },
  },
  "gallery-13": {
    slug: "gallery-13",
    width: 1170,
    height: 780,
    aspect: 1.5,
    widths: [390, 585, 878, 1170],
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZwDA3CC0AzFh2MkToAD+2lJK8cwIAZV02SBO84CJYzacvs6dKDhqXbPElGuQuyXyivSsWoW1es69w4l9AAAA",
    alt: { en: "A row of treadmills in a corridor beneath a 'Mind over matter' wall graphic and a howling-wolf metal wall sculpture", ar: "صف من أجهزة الجري في ممر أسفل عبارة جدارية 'العقل يتغلب على الجسد' ومنحوتة معدنية لذئب عاوٍ على الحائط" },
  },
  "logo-wordmark": {
    slug: "logo-wordmark",
    width: 813,
    height: 281,
    aspect: 2.8932,
    widths: [271, 407, 610, 813],
    blurDataURL: "data:image/webp;base64,UklGRjYBAABXRUJQVlA4WAoAAAAQAAAAEwAABgAAQUxQSI0AAAAAbdXj78/PUFjEvNnNk+DTr63Z46QDAKl0V7tVvqTdkFKV03hE1KrFuwAQ0S23r6LbqrqBc8WagH3Uedh9AFq1LNQAULe/0J+C6LaIpuGgvDIAn2gAGQAVGRBVOgpUdSQOITUTAAYjAwBUbEJeY2RTalpnTmY6AAICAAEACoRqYGVjoJ2/g7aGwkAAAwAAVlA4IIIAAADQAwCdASoUAAcAPzmGulOvKSWisAgB4CcJbACdL1ABfFCBYhIl9gAA+nZxdknZTvWPZV5jxdumSyI/W/We44jjtiXXZ4E2EJKaCGyy5e1PsgYP1Ipc8T37Qg+t/S3uzENlOe7YRWtdkY+SEwflxcW4KMdSlr+GcC9r4VxqTiP9bgAA",
    alt: { en: "Theeb Fitness wordmark logo in red and white", ar: "شعار ذيب فيتنس الكتابي باللونين الأحمر والأبيض" },
  },
  "logo-mark-square": {
    slug: "logo-mark-square",
    width: 1600,
    height: 1600,
    aspect: 1,
    widths: [400, 600, 900, 1200],
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUABQAPzmWwlmvKqcjqAgB4CcJaQAALnXEa8/xEAAA/srksL2Fe9eyC9i85cGDOAtdy8CAAAA=",
    alt: { en: "Square Theeb Fitness logo with a howling wolf emblem and wordmark on a dark background", ar: "شعار ذيب فيتنس المربع يضم رمز الذئب العاوي والاسم على خلفية داكنة" },
  },
  "wolf-mark": {
    slug: "wolf-mark",
    width: 384,
    height: 384,
    aspect: 1,
    widths: [128, 192, 288, 384],
    blurDataURL: "data:image/webp;base64,UklGRpoBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSEQBAAABkHPbtrG9wtc553k+27ZtVY7tdLbRWZ2ddLZt27ZtVanSvYmICQBEkeRuo8d0TxFU8BSly9lnp7dsOPXiXHdEACFo58vh4eCloYOfHQpHEULubPNG8bt5KwTv1c9iEOHIWtQcut04uRCXpZcVRtwwUXHZOLn3BfyFU9PwutsRQxn4I7Xgy4vlUPMkot11ENj6pgWt2H8Yh9MD567EjOlXo4JRDo3Gi+nrd0zAJfR1ZX061D0Pw6HPuX3D8KbvHVVxGHsKNTpeWT8Vav+OxxGl6VsuLoOPTNpOysc5CKAsOYnDqrkFz736/bs3A/PIfR6C79169s0k+elgDyHyfQ5jzkLJx3KmZiAAPr3dtA/1GMO/5GFmqmZG/KtpGMbEP0OM//f9PhsFjIa792a1Li5qmnzjcScMT8XtvOnapUvXtvf2xQBWUDggMAAAAPACAJ0BKhQAFAA/OY6+V68ppiOoCqngJwlpAAA+fnYAAP7u6ugdWlYrKx6apQQAAA==",
    alt: { en: "Outline emblem of a howling wolf inside a circle, the Theeb Fitness brand mark", ar: "شعار الذئب العاوي داخل دائرة، الرمز المميز لعلامة ذيب فيتنس" },
  },
} as const satisfies Record<string, MediaAsset>;

export type MediaSlug = keyof typeof MEDIA;

/** Builds a srcSet string ("/media/slug-360.webp 360w, ...") for one format. */
export function srcSet(slug: string, format: "avif" | "webp"): string {
  const asset = (MEDIA as Record<string, MediaAsset>)[slug];
  if (!asset) throw new Error(`Unknown media slug: ${slug}`);
  return asset.widths.map((w) => `/media/${slug}-${w}.${format} ${w}w`).join(", ");
}

/** Returns a single image URL (WebP) at the given width, or the largest available. */
export function src(slug: string, width?: number): string {
  const asset = (MEDIA as Record<string, MediaAsset>)[slug];
  if (!asset) throw new Error(`Unknown media slug: ${slug}`);
  const w = width ?? asset.widths[asset.widths.length - 1];
  const closest = asset.widths.includes(w)
    ? w
    : asset.widths.reduce((best, candidate) =>
        Math.abs(candidate - w) < Math.abs(best - w) ? candidate : best,
      );
  return `/media/${slug}-${closest}.webp`;
}
